# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# excludes: regex
#
# common utils
#
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
#
########### Optional ##########
#
# shell
#
# - repo: https://github.com/jumanjihouse/pre-commit-hooks
#   rev: 1.11.2
#   hooks:
#     - id: shellcheck
#       args: ["--color=always", "--shell=bash", "-x"]
#       additional_dependencies: [shellcheck]
#
# C/C++
#
# - repo: https://github.com/cheshirekow/cmake-format-precommit
#   rev: v0.6.7
#   hooks:
#   - id: cmake-format
#
# python
#
# - repo: https://github.com/psf/black
#   rev: 19.10b0
#   hooks:
#   - id: black
#
# - repo: https://github.com/PyCQA/flake8
#   rev: 3.7.9
#   hooks:
#   - id: flake8
#
# - repo: https://github.com/asottile/reorder_python_imports
#   rev: v1.9.0
#   hooks:
#     - id: reorder-python-imports
#       language_version: python3
#
# - repo: https://github.com/asottile/pyupgrade
#   rev: v1.16.2
#   hooks:
#     - id: pyupgrade
#
# rust
#
# - repo: https://github.com/doublify/pre-commit-rust
#   rev: master
#   hooks:
#   -   id: fmt
#   -   id: cargo-check
